name: notes2
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: 1.10.17
  auto_route: ^1.0.2
  cupertino_icons: 1.0.2
  dfunc: 0.6.2
  firebase_auth: 1.0.1
  firebase_core: 1.0.2
  flutter_bloc: 7.0.0
  freezed_annotation: 0.14.1
  get_it: 6.0.0
  google_sign_in: 5.0.1
  injectable: 1.2.2
  oxidized: 4.1.0
  uuid: 3.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^1.0.2
  build_runner: 1.12.2
  freezed: 0.14.1+1
  injectable_generator: 1.2.2
  lint: 1.5.3

flutter:
  uses-material-design: true

  assets:
    - GoogleService-Info.plist
